package require -exact qsys 15.0
set_module_property NAME loop_pipeline_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME loop_pipeline_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SUPPORTED_DEVICE_FAMILIES {"Arria 10"}
set_module_assignment hls.cosim.name {loop_pipeline}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL loop_pipeline_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_ver.sv SYSTEM_VERILOG PATH linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_altera_syncram_wrapped.sv SYSTEM_VERILOG PATH ip/acl_altera_syncram_wrapped.sv
add_fileset_file acl_scfifo_wrapped.sv SYSTEM_VERILOG PATH ip/acl_scfifo_wrapped.sv
add_fileset_file acl_ecc_decoder.sv SYSTEM_VERILOG PATH ip/acl_ecc_decoder.sv
add_fileset_file acl_ecc_encoder.sv SYSTEM_VERILOG PATH ip/acl_ecc_encoder.sv
add_fileset_file acl_ecc.svh SYSTEM_VERILOG PATH ip/acl_ecc.svh
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file acl_mid_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_mid_speed_fifo.sv
add_fileset_file acl_latency_one_ram_fifo.sv SYSTEM_VERILOG PATH ip/acl_latency_one_ram_fifo.sv
add_fileset_file acl_latency_zero_ram_fifo.sv SYSTEM_VERILOG PATH ip/acl_latency_zero_ram_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file acl_tessellated_incr_decr_decr.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_decr.sv
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file loop_pipeline_function_wrapper.sv SYSTEM_VERILOG PATH ip/loop_pipeline_function_wrapper.sv
add_fileset_file loop_pipeline_function.sv SYSTEM_VERILOG PATH ip/loop_pipeline_function.sv
add_fileset_file loop_pipeline_bb_B0_runOnce.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B0_runOnce.sv
add_fileset_file loop_pipeline_bb_B0_runOnce_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B0_runOnce_stall_region.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_1.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_1.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_4.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_4.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_3_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_3_reg.sv
add_fileset_file loop_pipeline_B0_runOnce_merge_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B0_runOnce_merge_reg.sv
add_fileset_file loop_pipeline_B0_runOnce_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B0_runOnce_branch.sv
add_fileset_file loop_pipeline_B0_runOnce_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B0_runOnce_merge.sv
add_fileset_file loop_pipeline_bb_B1_start.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B1_start.sv
add_fileset_file loop_pipeline_bb_B1_start_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B1_start_stall_region.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zssa_replace_phi30_26.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zssa_replace_phi30_26.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_20_loop_pipeline160.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_20_loop_pipeline160.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_21_loop_pipeline163.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_21_loop_pipeline163.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_22_loop_pipeline166.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_22_loop_pipeline166.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_23_loop_pipeline169.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_23_loop_pipeline169.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_24_loop_pipeline172.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_24_loop_pipeline172.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_25_loop_pipeline175.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_25_loop_pipeline175.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_26_loop_pipeline178.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_26_loop_pipeline178.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_27_loop_pipeline181.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_27_loop_pipeline181.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_28_loop_pipeline184.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_28_loop_pipeline184.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_29_loop_pipeline187.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_29_loop_pipeline187.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_30_loop_pipeline190.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_30_loop_pipeline190.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_31_loop_pipeline193.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_31_loop_pipeline193.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_32_loop_pipeline196.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_32_loop_pipeline196.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_33_loop_pipeline199.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_33_loop_pipeline199.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_34_loop_pipeline202.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_34_loop_pipeline202.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_35_loop_pipeline205.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_35_loop_pipeline205.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_36_loop_pipeline208.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_36_loop_pipeline208.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_37_loop_pipeline211.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_37_loop_pipeline211.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_38_loop_pipeline214.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_38_loop_pipeline214.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_39_loop_pipeline217.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_39_loop_pipeline217.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_3_loop_pipeline77.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_3_loop_pipeline77.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_2_loop_pipeline34.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_2_loop_pipeline34.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipelined_i5_p1024i5_pre1_80.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipelined_i5_p1024i5_pre1_80.sv
add_fileset_file loop_pipeline_readdata_reg_pre1_0.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre1_0.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2552_83.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2552_83.sv
add_fileset_file loop_pipeline_readdata_reg_pre2552_1.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre2552_1.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2563_86.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2563_86.sv
add_fileset_file loop_pipeline_readdata_reg_pre2563_2.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre2563_2.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2574_89.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2574_89.sv
add_fileset_file loop_pipeline_readdata_reg_pre2574_3.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre2574_3.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_10_loop_pipeline110.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_10_loop_pipeline110.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_10_loop_pipeline10.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_10_loop_pipeline10.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_11_loop_pipeline113.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_11_loop_pipeline113.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_11_loop_pipeline11.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_11_loop_pipeline11.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_12_loop_pipeline116.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_12_loop_pipeline116.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_12_loop_pipeline12.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_12_loop_pipeline12.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_13_loop_pipeline119.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_13_loop_pipeline119.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_13_loop_pipeline13.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_13_loop_pipeline13.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_14_loop_pipeline122.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_14_loop_pipeline122.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_14_loop_pipeline14.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_14_loop_pipeline14.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_15_loop_pipeline125.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_15_loop_pipeline125.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_15_loop_pipeline15.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_15_loop_pipeline15.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_16_loop_pipeline128.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_16_loop_pipeline128.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_16_loop_pipeline16.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_16_loop_pipeline16.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_17_loop_pipeline131.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_17_loop_pipeline131.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_17_loop_pipeline17.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_17_loop_pipeline17.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_18_loop_pipeline134.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_18_loop_pipeline134.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_18_loop_pipeline18.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_18_loop_pipeline18.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_19_loop_pipeline137.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_19_loop_pipeline137.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_19_loop_pipeline19.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_19_loop_pipeline19.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_4_loop_pipeline92.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_4_loop_pipeline92.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_4_loop_pipeline4.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_4_loop_pipeline4.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_5_loop_pipeline95.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_5_loop_pipeline95.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_5_loop_pipeline5.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_5_loop_pipeline5.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_6_loop_pipeline98.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_6_loop_pipeline98.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_6_loop_pipeline6.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_6_loop_pipeline6.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_7_loop_pipeline101.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_7_loop_pipeline101.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_7_loop_pipeline7.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_7_loop_pipeline7.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_8_loop_pipeline104.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_8_loop_pipeline104.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_8_loop_pipeline8.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_8_loop_pipeline8.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_9_loop_pipeline107.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_9_loop_pipeline107.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_9_loop_pipeline9.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_9_loop_pipeline9.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_23.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_23.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_22_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_22_reg.sv
add_fileset_file loop_pipeline_i_iord_bl_do_unnamed_1_loop_pipeline29.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_iord_bl_do_unnamed_1_loop_pipeline29.sv
add_fileset_file loop_pipeline_i_sfc_s_c0_in_wt_entry_s_c0_enter1_loop_pipeline7.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_s_c0_in_wt_entry_s_c0_enter1_loop_pipeline7.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zexit_loop_pipeline19.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zexit_loop_pipeline19.sv
add_fileset_file loop_pipeline_i_sfc_logic_s_c0_in_wt_entA000Znter1_loop_pipeline8.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_logic_s_c0_in_wt_entA000Znter1_loop_pipeline8.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going31_12.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going31_12.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i1_notexitcond32_15.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i1_notexitcond32_15.sv
add_fileset_file loop_pipeline_B1_start_merge_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B1_start_merge_reg.sv
add_fileset_file loop_pipeline_B1_start_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B1_start_branch.sv
add_fileset_file loop_pipeline_B1_start_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B1_start_merge.sv
add_fileset_file loop_pipeline_bb_B2.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B2.sv
add_fileset_file loop_pipeline_bb_B2_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B2_stall_region.sv
add_fileset_file loop_pipeline_i_sfc_s_c0_in_for_cond1_prA000Z342_loop_pipeline220.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_s_c0_in_for_cond1_prA000Z342_loop_pipeline220.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zt38_loop_pipeline391.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zt38_loop_pipeline391.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zine390_full_detector.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zine390_full_detector.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zipeline409_data_fifo.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zipeline409_data_fifo.sv
add_fileset_file loop_pipeline_i_sfc_logic_s_c0_in_for_coA000Z342_loop_pipeline221.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_logic_s_c0_in_for_coA000Z342_loop_pipeline221.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i23_263.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i23_263.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1013_293.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1013_293.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1114_296.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1114_296.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1215_299.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1215_299.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_124_266.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_124_266.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1316_302.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1316_302.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1417_305.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1417_305.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1518_308.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1518_308.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1619_311.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1619_311.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1720_314.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1720_314.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1821_317.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1821_317.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1922_320.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1922_320.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_225_269.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_225_269.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_326_272.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_326_272.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_47_275.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_47_275.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_58_278.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_58_278.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_69_281.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_69_281.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_710_284.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_710_284.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_811_287.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_811_287.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_912_290.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_912_290.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z_t6_loop_pipeline245.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z_t6_loop_pipeline245.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Z_05_loop_pipeline252.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Z_05_loop_pipeline252.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_40_loop_pipeline383.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_40_loop_pipeline383.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_41_loop_pipeline386.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_41_loop_pipeline386.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going_230.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going_230.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i20_pop8_248.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i20_pop8_248.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i24_zz13e3A000Zop7_loop_pipeline255.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i24_zz13e3A000Zop7_loop_pipeline255.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i32_i_029_pop9_259.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i32_i_029_pop9_259.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i4_cleanups_pop11_225.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i4_cleanups_pop11_225.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i4_initerations_pop10_233.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i4_initerations_pop10_233.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i6_fpgaindvars_iv_pop6_363.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i6_fpgaindvars_iv_pop6_363.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i1_lastiniteration_242.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i1_lastiniteration_242.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i1_notexitcond_369.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i1_notexitcond_369.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i20_push8_344.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i20_push8_344.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i24_zz13eA000Zsh7_loop_pipeline356.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i24_zz13eA000Zsh7_loop_pipeline356.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i32_i_029_push9_360.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i32_i_029_push9_360.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i4_cleanups_push11_376.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i4_cleanups_push11_376.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i4_initerations_push10_238.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i4_initerations_push10_238.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i6_fpgaindvars_iv_push6_380.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i6_fpgaindvars_iv_push6_380.sv
add_fileset_file loop_pipeline_B2_merge_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B2_merge_reg.sv
add_fileset_file loop_pipeline_B2_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B2_branch.sv
add_fileset_file loop_pipeline_B2_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B2_merge.sv
add_fileset_file loop_pipeline_bb_B3.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B3.sv
add_fileset_file loop_pipeline_bb_B3_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B3_stall_region.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z927_loop_pipeline397.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z927_loop_pipeline397.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zs_pms_vm_pms_d28_394.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zs_pms_vm_pms_d28_394.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_44_loop_pipeline407.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_44_loop_pipeline407.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_404.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_404.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_403_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_403_reg.sv
add_fileset_file loop_pipeline_i_iowr_bl_return_unnamed_43_loop_pipeline402.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_iowr_bl_return_unnamed_43_loop_pipeline402.sv
add_fileset_file loop_pipeline_B3_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B3_branch.sv
add_fileset_file loop_pipeline_B3_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B3_merge.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_sr.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_sr.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_valid_fifo.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_valid_fifo.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_sr.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_sr.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_valid_fifo.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_valid_fifo.sv
add_fileset_file loop_pipeline_loop_limiter_0.sv SYSTEM_VERILOG PATH ip/loop_pipeline_loop_limiter_0.sv
add_fileset_file loop_pipeline_bb_B2_sr_1.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B2_sr_1.sv
add_fileset_file loop_pipeline_bb_B3_sr_0.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B3_sr_0.sv
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file acl_arb2.v SYSTEM_VERILOG PATH ip/acl_arb2.v
add_fileset_file acl_ic_to_avm.v SYSTEM_VERILOG PATH ip/acl_ic_to_avm.v
add_fileset_file loop_pipeline_internal.v SYSTEM_VERILOG PATH loop_pipeline_internal.v

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL loop_pipeline_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_ver.sv SYSTEM_VERILOG PATH linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_altera_syncram_wrapped.sv SYSTEM_VERILOG PATH ip/acl_altera_syncram_wrapped.sv
add_fileset_file acl_scfifo_wrapped.sv SYSTEM_VERILOG PATH ip/acl_scfifo_wrapped.sv
add_fileset_file acl_ecc_decoder.sv SYSTEM_VERILOG PATH ip/acl_ecc_decoder.sv
add_fileset_file acl_ecc_encoder.sv SYSTEM_VERILOG PATH ip/acl_ecc_encoder.sv
add_fileset_file acl_ecc.svh SYSTEM_VERILOG PATH ip/acl_ecc.svh
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file acl_mid_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_mid_speed_fifo.sv
add_fileset_file acl_latency_one_ram_fifo.sv SYSTEM_VERILOG PATH ip/acl_latency_one_ram_fifo.sv
add_fileset_file acl_latency_zero_ram_fifo.sv SYSTEM_VERILOG PATH ip/acl_latency_zero_ram_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file acl_tessellated_incr_decr_decr.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_decr.sv
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file loop_pipeline_function_wrapper.sv SYSTEM_VERILOG PATH ip/loop_pipeline_function_wrapper.sv
add_fileset_file loop_pipeline_function.sv SYSTEM_VERILOG PATH ip/loop_pipeline_function.sv
add_fileset_file loop_pipeline_bb_B0_runOnce.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B0_runOnce.sv
add_fileset_file loop_pipeline_bb_B0_runOnce_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B0_runOnce_stall_region.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_1.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_1.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_4.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_4.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_3_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_wt_limpush_3_reg.sv
add_fileset_file loop_pipeline_B0_runOnce_merge_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B0_runOnce_merge_reg.sv
add_fileset_file loop_pipeline_B0_runOnce_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B0_runOnce_branch.sv
add_fileset_file loop_pipeline_B0_runOnce_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B0_runOnce_merge.sv
add_fileset_file loop_pipeline_bb_B1_start.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B1_start.sv
add_fileset_file loop_pipeline_bb_B1_start_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B1_start_stall_region.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zssa_replace_phi30_26.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zssa_replace_phi30_26.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_20_loop_pipeline160.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_20_loop_pipeline160.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_21_loop_pipeline163.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_21_loop_pipeline163.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_22_loop_pipeline166.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_22_loop_pipeline166.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_23_loop_pipeline169.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_23_loop_pipeline169.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_24_loop_pipeline172.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_24_loop_pipeline172.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_25_loop_pipeline175.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_25_loop_pipeline175.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_26_loop_pipeline178.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_26_loop_pipeline178.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_27_loop_pipeline181.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_27_loop_pipeline181.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_28_loop_pipeline184.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_28_loop_pipeline184.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_29_loop_pipeline187.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_29_loop_pipeline187.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_30_loop_pipeline190.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_30_loop_pipeline190.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_31_loop_pipeline193.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_31_loop_pipeline193.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_32_loop_pipeline196.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_32_loop_pipeline196.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_33_loop_pipeline199.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_33_loop_pipeline199.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_34_loop_pipeline202.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_34_loop_pipeline202.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_35_loop_pipeline205.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_35_loop_pipeline205.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_36_loop_pipeline208.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_36_loop_pipeline208.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_37_loop_pipeline211.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_37_loop_pipeline211.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_38_loop_pipeline214.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_38_loop_pipeline214.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_39_loop_pipeline217.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_39_loop_pipeline217.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_3_loop_pipeline77.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_3_loop_pipeline77.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_2_loop_pipeline34.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Zed_2_loop_pipeline34.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipelined_i5_p1024i5_pre1_80.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipelined_i5_p1024i5_pre1_80.sv
add_fileset_file loop_pipeline_readdata_reg_pre1_0.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre1_0.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2552_83.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2552_83.sv
add_fileset_file loop_pipeline_readdata_reg_pre2552_1.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre2552_1.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2563_86.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2563_86.sv
add_fileset_file loop_pipeline_readdata_reg_pre2563_2.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre2563_2.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2574_89.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z5_p1024i5_pre2574_89.sv
add_fileset_file loop_pipeline_readdata_reg_pre2574_3.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_pre2574_3.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_10_loop_pipeline110.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_10_loop_pipeline110.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_10_loop_pipeline10.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_10_loop_pipeline10.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_11_loop_pipeline113.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_11_loop_pipeline113.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_11_loop_pipeline11.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_11_loop_pipeline11.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_12_loop_pipeline116.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_12_loop_pipeline116.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_12_loop_pipeline12.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_12_loop_pipeline12.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_13_loop_pipeline119.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_13_loop_pipeline119.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_13_loop_pipeline13.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_13_loop_pipeline13.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_14_loop_pipeline122.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_14_loop_pipeline122.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_14_loop_pipeline14.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_14_loop_pipeline14.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_15_loop_pipeline125.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_15_loop_pipeline125.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_15_loop_pipeline15.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_15_loop_pipeline15.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_16_loop_pipeline128.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_16_loop_pipeline128.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_16_loop_pipeline16.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_16_loop_pipeline16.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_17_loop_pipeline131.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_17_loop_pipeline131.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_17_loop_pipeline17.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_17_loop_pipeline17.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_18_loop_pipeline134.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_18_loop_pipeline134.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_18_loop_pipeline18.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_18_loop_pipeline18.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Z_19_loop_pipeline137.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Z_19_loop_pipeline137.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_19_loop_pipeline19.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_19_loop_pipeline19.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_4_loop_pipeline92.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_4_loop_pipeline92.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_4_loop_pipeline4.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_4_loop_pipeline4.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_5_loop_pipeline95.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_5_loop_pipeline95.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_5_loop_pipeline5.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_5_loop_pipeline5.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_6_loop_pipeline98.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zed_6_loop_pipeline98.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_6_loop_pipeline6.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_6_loop_pipeline6.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_7_loop_pipeline101.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_7_loop_pipeline101.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_7_loop_pipeline7.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_7_loop_pipeline7.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_8_loop_pipeline104.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_8_loop_pipeline104.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_8_loop_pipeline8.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_8_loop_pipeline8.sv
add_fileset_file loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_9_loop_pipeline107.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_load_local_pipA000Zd_9_loop_pipeline107.sv
add_fileset_file loop_pipeline_readdata_reg_unnamed_9_loop_pipeline9.sv SYSTEM_VERILOG PATH ip/loop_pipeline_readdata_reg_unnamed_9_loop_pipeline9.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_23.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_23.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_22_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_throttle_i1_throttle_pop_22_reg.sv
add_fileset_file loop_pipeline_i_iord_bl_do_unnamed_1_loop_pipeline29.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_iord_bl_do_unnamed_1_loop_pipeline29.sv
add_fileset_file loop_pipeline_i_sfc_s_c0_in_wt_entry_s_c0_enter1_loop_pipeline7.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_s_c0_in_wt_entry_s_c0_enter1_loop_pipeline7.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zexit_loop_pipeline19.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zexit_loop_pipeline19.sv
add_fileset_file loop_pipeline_i_sfc_logic_s_c0_in_wt_entA000Znter1_loop_pipeline8.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_logic_s_c0_in_wt_entA000Znter1_loop_pipeline8.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going31_12.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going31_12.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i1_notexitcond32_15.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i1_notexitcond32_15.sv
add_fileset_file loop_pipeline_B1_start_merge_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B1_start_merge_reg.sv
add_fileset_file loop_pipeline_B1_start_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B1_start_branch.sv
add_fileset_file loop_pipeline_B1_start_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B1_start_merge.sv
add_fileset_file loop_pipeline_bb_B2.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B2.sv
add_fileset_file loop_pipeline_bb_B2_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B2_stall_region.sv
add_fileset_file loop_pipeline_i_sfc_s_c0_in_for_cond1_prA000Z342_loop_pipeline220.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_s_c0_in_for_cond1_prA000Z342_loop_pipeline220.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zt38_loop_pipeline391.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zt38_loop_pipeline391.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zine390_full_detector.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zine390_full_detector.sv
add_fileset_file loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zipeline409_data_fifo.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_sfc_exit_s_c0_A000Zipeline409_data_fifo.sv
add_fileset_file loop_pipeline_i_sfc_logic_s_c0_in_for_coA000Z342_loop_pipeline221.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_sfc_logic_s_c0_in_for_coA000Z342_loop_pipeline221.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i23_263.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i23_263.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1013_293.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1013_293.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1114_296.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1114_296.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1215_299.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1215_299.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_124_266.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_124_266.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1316_302.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1316_302.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1417_305.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1417_305.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1518_308.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1518_308.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1619_311.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1619_311.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1720_314.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1720_314.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1821_317.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1821_317.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1922_320.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_1922_320.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_225_269.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_225_269.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_326_272.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_326_272.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_47_275.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_47_275.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_58_278.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_58_278.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_69_281.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_69_281.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_710_284.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_710_284.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_811_287.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_811_287.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_912_290.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_conv_i1_i_i_912_290.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z_t6_loop_pipeline245.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z_t6_loop_pipeline245.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Z_05_loop_pipeline252.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Z_05_loop_pipeline252.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_40_loop_pipeline383.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_40_loop_pipeline383.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_41_loop_pipeline386.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_41_loop_pipeline386.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going_230.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going_230.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i20_pop8_248.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i20_pop8_248.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i24_zz13e3A000Zop7_loop_pipeline255.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i24_zz13e3A000Zop7_loop_pipeline255.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i32_i_029_pop9_259.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i32_i_029_pop9_259.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i4_cleanups_pop11_225.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i4_cleanups_pop11_225.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i4_initerations_pop10_233.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i4_initerations_pop10_233.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pop_i6_fpgaindvars_iv_pop6_363.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pop_i6_fpgaindvars_iv_pop6_363.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i1_lastiniteration_242.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i1_lastiniteration_242.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i1_notexitcond_369.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i1_notexitcond_369.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i20_push8_344.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i20_push8_344.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i24_zz13eA000Zsh7_loop_pipeline356.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i24_zz13eA000Zsh7_loop_pipeline356.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i32_i_029_push9_360.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i32_i_029_push9_360.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i4_cleanups_push11_376.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i4_cleanups_push11_376.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i4_initerations_push10_238.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i4_initerations_push10_238.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_i6_fpgaindvars_iv_push6_380.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_i6_fpgaindvars_iv_push6_380.sv
add_fileset_file loop_pipeline_B2_merge_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B2_merge_reg.sv
add_fileset_file loop_pipeline_B2_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B2_branch.sv
add_fileset_file loop_pipeline_B2_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B2_merge.sv
add_fileset_file loop_pipeline_bb_B3.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B3.sv
add_fileset_file loop_pipeline_bb_B3_stall_region.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B3_stall_region.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z927_loop_pipeline397.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i20_A000Z927_loop_pipeline397.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zs_pms_vm_pms_d28_394.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_dest_i24_A000Zs_pms_vm_pms_d28_394.sv
add_fileset_file loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_44_loop_pipeline407.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_ffwd_source_i2A000Z_44_loop_pipeline407.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_404.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_404.sv
add_fileset_file loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_403_reg.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_push_token_i1_throttle_push_403_reg.sv
add_fileset_file loop_pipeline_i_iowr_bl_return_unnamed_43_loop_pipeline402.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_iowr_bl_return_unnamed_43_loop_pipeline402.sv
add_fileset_file loop_pipeline_B3_branch.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B3_branch.sv
add_fileset_file loop_pipeline_B3_merge.sv SYSTEM_VERILOG PATH ip/loop_pipeline_B3_merge.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_sr.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_sr.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_valid_fifo.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going31_11_valid_fifo.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_sr.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_sr.sv
add_fileset_file loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_valid_fifo.sv SYSTEM_VERILOG PATH ip/loop_pipeline_i_llvm_fpga_pipeline_keep_going_229_valid_fifo.sv
add_fileset_file loop_pipeline_loop_limiter_0.sv SYSTEM_VERILOG PATH ip/loop_pipeline_loop_limiter_0.sv
add_fileset_file loop_pipeline_bb_B2_sr_1.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B2_sr_1.sv
add_fileset_file loop_pipeline_bb_B3_sr_0.sv SYSTEM_VERILOG PATH ip/loop_pipeline_bb_B3_sr_0.sv
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file acl_arb2.v SYSTEM_VERILOG PATH ip/acl_arb2.v
add_fileset_file acl_ic_to_avm.v SYSTEM_VERILOG PATH ip/acl_ic_to_avm.v
add_fileset_file loop_pipeline_internal.v SYSTEM_VERILOG PATH loop_pipeline_internal.v

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### The component invocation protocol interface (call)
add_interface call conduit sink
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_assignment call hls.cosim.name {$call}
add_interface_port call start valid input 1
add_interface_port call busy stall output 1

#### The component return protocol interface (return)
add_interface return conduit source
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_assignment return hls.cosim.name {$return}
add_interface_port return done valid output 1
add_interface_port return stall stall input 1

#### The component return data interface (returndata)
add_interface returndata conduit source
set_interface_property returndata associatedClock clock
set_interface_property returndata associatedReset reset
set_interface_assignment returndata hls.cosim.name {$returndata}
add_interface_port returndata returndata data output 20

#### Parameter A interface
add_interface A conduit sink
set_interface_property A associatedClock clock
set_interface_property A associatedReset reset
set_interface_assignment A hls.cosim.name {A}
add_interface_port A A data input 64

#### Master interface avmm_0_rw with base address 0
add_interface avmm_0_rw avalon start
set_interface_property avmm_0_rw ENABLED true
set_interface_property avmm_0_rw associatedClock clock
set_interface_property avmm_0_rw burstOnBurstBoundariesOnly false
set_interface_property avmm_0_rw doStreamReads false
set_interface_property avmm_0_rw doStreamWrites false
set_interface_property avmm_0_rw linewrapBursts false
set_interface_property avmm_0_rw readWaitTime 0
set_interface_property avmm_0_rw readLatency 1
add_interface_port avmm_0_rw avmm_0_rw_address address output 64
add_interface_port avmm_0_rw avmm_0_rw_byteenable byteenable output 8
add_interface_port avmm_0_rw avmm_0_rw_read read output 1
add_interface_port avmm_0_rw avmm_0_rw_readdata readdata input 64
add_interface_port avmm_0_rw avmm_0_rw_write write output 1
add_interface_port avmm_0_rw avmm_0_rw_writedata writedata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
